//created on: Mar 13, 2014
package cz.muni.fi.civ.newohybat.bpmn

//list any import classes here.
import cz.muni.fi.civ.newohybat.persistence.facade.dto.CityDTO;
import cz.muni.fi.civ.newohybat.persistence.facade.dto.UnitTypeDTO;
import org.drools.runtime.process.WorkflowProcessInstance;
import org.drools.runtime.process.ProcessInstance;
import java.util.HashMap;
import java.util.Map;

import cz.muni.fi.civ.newohybat.drools.events.UnitEvent;


//declare any global variables here
declare UnitEvent
	@role( event )
	//@expires( 1ms )
end


rule "City Start Build Unit"
	activation-group "buildUnit"
	when
		$city:CityDTO(
			currentUnit!=null
			,$currentUnit:currentUnit
			,$cityId:id
		) @watch(currentUnit)
		$unitType:UnitTypeDTO(
			ident==$currentUnit
			,$ident:ident
		) @watch(!*)
		not WorkflowProcessInstance(
			getProcessId()=="cz.muni.fi.civ.newohybat.bpmn.buildUnit"
			,((CityDTO)getVariable("city")).getId()==$cityId
		)
	then
		Map params = new HashMap();
		params.put("unitType",$unitType);
		params.put("city",$city);
		params.put("unit",null);
		params.put("resourcesSpent",0);
		ProcessInstance pi = kcontext.getKnowledgeRuntime().createProcessInstance("cz.muni.fi.civ.newohybat.bpmn.buildUnit",params);
		kcontext.getKnowledgeRuntime().startProcessInstance(pi.getId());
end

rule "Cancel Unit Build"
	activation-group "buildUnit"
	when
		$city:CityDTO(
			$currentUnit:currentUnit
			,$cityId:id
		) @watch(!*)
		$pc:UnitEvent(
			cityId==$cityId
		) from entry-point ActionCanceledStream
		$pi:WorkflowProcessInstance(
			getProcessId()=="cz.muni.fi.civ.newohybat.bpmn.buildUnit"
			,((CityDTO)getVariable("city")).getId()==$cityId
			,$processId:id
		)
	then
		modify($city){
			setCurrentUnit(null)
		}
		kcontext.getKnowledgeRuntime().signalEvent("cancel",null,$processId);
end